module.exports = {
  $schema: 'https://docs.renovatebot.com/renovate-schema.json',
  extends: [
    'config:recommended',
    'helpers:pinGitHubActionDigests',
    ':configMigration',
    ':pinDevDependencies',
  ],
  rebaseWhen: 'never',
  branchPrefix: 'renovate/',
  platform: 'github',
  platformCommit: 'disabled',
  repositories: ['better-notify/better-notify'],
  onboardingPrTitle: 'configure renovate',
  onboarding: true,
  requireConfig: 'optional',
  prConcurrentLimit: 5,
  branchConcurrentLimit: 5,
  prHourlyLimit: 5,
  addLabels: ['dependencies'],
  minimumReleaseAge: '1 day',
  packageRules: [
    {
      matchUpdateTypes: ['patch'],
      groupName: 'all patch dependencies',
      groupSlug: 'all-patch',
      matchPackageNames: ['*'],
    },
    {
      matchUpdateTypes: ['minor'],
      groupName: 'all minor dependencies',
      groupSlug: 'all-minor',
      matchPackageNames: ['*'],
    },
    {
      groupName: 'rolldown',
      groupSlug: 'rolldown',
      matchPackageNames: ['/rolldown/'],
      matchDepTypes: ['dependencies'],
    },
    {
      groupName: 'fumadocs',
      groupSlug: 'fumadocs',
      matchPackageNames: ['/fumadocs/'],
      matchDepTypes: ['dependencies'],
    },
    {
      groupName: 'react-email',
      groupSlug: 'react-email',
      matchPackageNames: ['/@react-email/', '/react-email/'],
      matchDepTypes: ['dependencies'],
    },
    {
      groupName: '@tanstack',
      groupSlug: '@tanstack',
      matchPackageNames: ['/@tanstack/'],
      matchDepTypes: ['dependencies'],
    },
    {
      groupName: 'cloudflare',
      groupSlug: 'cloudflare',
      matchPackageNames: ['/@cloudflare/', '/wrangler/'],
      matchDepTypes: ['dependencies'],
    },
    {
      groupName: 'vitest',
      groupSlug: 'vitest',
      matchPackageNames: ['/vitest/'],
      matchDepTypes: ['dependencies'],
    },
  ],
  ignorePaths: ['**/node_modules/**'],
};
