name: Check for job errors
description: Check for Github job errors

inputs:
  needs:
    description: The Github job needs
    required: true

runs:
  using: composite
  steps:
    - name: Check jobs for errors
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
      with:
        script: |
          const checkJobsForErrors = require('./.github/workflows/js/check-jobs-for-errors.cjs');
          checkJobsForErrors({ core, jobs: ${{ inputs.needs }} });
