import {
  Anchor,
  ArrowsLeftRight,
  At,
  Atom,
  Bell,
  BookOpen,
  Books,
  BracketsCurly,
  Broadcast,
  Bug,
  ChatText,
  ClockCounterClockwise,
  Cloud,
  Code,
  Crosshair,
  Database,
  DiscordLogo,
  Envelope,
  Export,
  Eye,
  FileCode,
  FileText,
  Fingerprint,
  Flask,
  Funnel,
  Gauge,
  GitFork,
  Globe,
  HardDrives,
  House,
  Layout,
  Lightbulb,
  Lightning,
  Megaphone,
  Newspaper,
  Notebook,
  Package,
  PaperPlane,
  Path,
  Plug,
  Pulse,
  Queue,
  Rocket,
  Scales,
  Shield,
  SlackLogo,
  Stack,
  Tag,
  TelegramLogo,
  Terminal,
  TestTube,
  TreeStructure,
  Truck,
  Warning,
  WebhooksLogo,
  Wrench,
} from '@phosphor-icons/react';
import { createElement } from 'react';

const TwilioLogo = ({ size = 18 }: { size?: number }) =>
  createElement(
    'svg',
    {
      width: size,
      height: size,
      viewBox: '0 0 256 256',
      fill: 'none',
      xmlns: 'http://www.w3.org/2000/svg',
    },
    createElement('circle', {
      cx: '128',
      cy: '128',
      r: '112',
      stroke: 'currentColor',
      strokeWidth: '16',
    }),
    createElement('circle', { cx: '96', cy: '96', r: '24', fill: 'currentColor' }),
    createElement('circle', { cx: '160', cy: '96', r: '24', fill: 'currentColor' }),
    createElement('circle', { cx: '96', cy: '160', r: '24', fill: 'currentColor' }),
    createElement('circle', { cx: '160', cy: '160', r: '24', fill: 'currentColor' }),
  );

export const iconMap = {
  Activity: Pulse,
  AmazonLogo: Globe,
  Anchor,
  ArrowsLeftRight,
  At,
  Atom,
  Bell,
  BookOpen,
  Books,
  Bug,
  ChatText,
  Cloud,
  Code,
  Crosshair,
  CurlyBraces: BracketsCurly,
  Database,
  DiscordLogo,
  Envelope,
  Export,
  Eye,
  FileCode,
  FileText,
  Fingerprint,
  FlaskRound: Flask,
  Funnel,
  Gauge,
  GitFork,
  Globe,
  History: ClockCounterClockwise,
  House,
  Layers: Stack,
  Layout,
  Lightbulb,
  Lightning,
  Megaphone,
  Newspaper,
  Notebook,
  Package,
  PaperPlane,
  Path,
  Plug,
  Queue,
  Radio: Broadcast,
  Rocket,
  Scales,
  Server: HardDrives,
  Shield,
  SlackLogo,
  Tag,
  TelegramLogo,
  TwilioLogo,
  Terminal,
  TestTube,
  TreeStructure,
  Truck,
  Warning,
  Webhooks: WebhooksLogo,
  Wrench,
} as const;
